Docstrings pep8
mariatzele/university-app pull request #10
Opened 2024-12-15 19:29 UTC by SRich-ing

Completed docstrings
Brought code in line with PEP-8 standards

2024-12-15 20:51 UTC, mariatzele commented
Why did you open another Pull Request for this? You already had https://github.com/mariatzele/university-app/pull/9 . Are you cancelling that?

2024-12-15 20:51 UTC, mariatzele commented on src/main.py
> +main.py
Why are the file names in top comments? This is not PEP8 standard

2024-12-15 20:52 UTC, mariatzele commented on src/gui/components/listview.py
> +        # treeview = ttk.Treeview(self.primary, show="headings")
I do not understand why this was commented out, won't this cause the headings to be missing?

2024-12-15 20:52 UTC, mariatzele commented on src/gui/components/listview.py
> +"""listview.py"""
File name comments at the top of the file are not part of PEP8

2024-12-15 21:00 UTC, mariatzele requested changes
This cannot be merged as is. Review the PEP8 Standard please:
https://peps.python.org/pep-0008/

The filenames as top comments is not mentioned there so I don't know why they are added. More importantly a treeview component is commented out in `listview.py` meaning it won't be shown. Based on this code and pull request details I don't see why this was done

2024-12-16 07:58 UTC, SRich-ing commented
> Why did you open another Pull Request for this? You already had #9 . Are you cancelling that?

I think deleting that additional .py file on the remote repository made it difficult for me to merge directly so it was easier to make a new branch in the time available. The earlier one can be merged or deleted, they don't conflict.

2024-12-16 07:59 UTC, SRich-ing commented
> This cannot be merged as is. Review the PEP8 Standard please: https://peps.python.org/pep-0008/
> 
> The filenames as top comments is not mentioned there so I don't know why they are added. More importantly a treeview component is commented out in `listview.py` meaning it won't be shown. Based on this code and pull request details I don't see why this was done

The modules require a header according to pylint - I updated with descriptions. 

The treeview component should have been deleted. It doesn't do anything anymore.

2024-12-16 08:01 UTC, SRich-ing commented on src/gui/components/listview.py
> +        # treeview = ttk.Treeview(self.primary, show="headings")
it's a duplicate. See the next row

2024-12-16 08:03 UTC, SRich-ing commented
> Completed docstrings Brought code in line with PEP-8 standards

Application has been tested with all five filters and tests run and confirmed to be OK

2024-12-16 18:17 UTC, merged