aesthetics update
mariatzele/university-app pull request #4
Opened 2024-12-10 18:41 UTC by SRich-ing

Colours and style updated

2024-12-10 19:31 UTC, mariatzele commented on src/data/db.py
> +        self.database = 'uni_app'
You cannot change these here. We don't all have the same password for the database. You should create a `.env` file as described in the README.md

2024-12-11 00:47 UTC, mariatzele requested changes
Please see my notes. Do not merge without removing the changes in db.py

2024-12-11 07:11 UTC, SRich-ing commented on src/data/db.py
> +        self.database = 'uni_app'
Agreed - left that in by mistake!

2024-12-11 09:54 UTC, sgtho approved these changes

2024-12-11 09:54 UTC, sgtho commented on src/data/db.py
> +        self.database = 'uni_app'
@SRich-ing Is that possible to create a database by following the README from your side? If so, we should all do that to make sure the process is suitable for everyone.

2024-12-11 09:55 UTC, sgtho approved these changes

2024-12-11 09:55 UTC, sgtho approved these changes

2024-12-11 09:55 UTC, sgtho approved these changes

2024-12-11 09:56 UTC, sgtho approved these changes

2024-12-11 09:58 UTC, sgtho approved these changes

2024-12-11 14:40 UTC, sgtho approved these changes

2024-12-11 14:58 UTC, merged